---

title: "Bike Shares Daily"
author: "Natarajan G"
date: "12/31/2019"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
  html_document:
    df_print: paged
    
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(lubridate)
library(ggplot2)
library(tidyverse)
library(plotly)
library(leaflet)
library(knitr)
library(DT)

trips_df <- read_csv('http://s3.amazonaws.com/assets.datacamp.com/production/course_6355/datasets/sanfran_bikeshare_joined_oneday.csv')

stations_df <- read_csv('http://s3.amazonaws.com/assets.datacamp.com/production/course_6355/datasets/stations_data.csv')


```

``` {r}

```

Overview
===================================== 

Column {data-width=500}
-----------------------------------------------------------------------

### Station Usage

```{r}

station_df <- trips_df %>%
  select(start_station_name, end_station_name) %>%
  rename(Start = start_station_name, End = end_station_name) %>%
  gather(key = Usage, value = Station)

station_gg <- ggplot(station_df,
                     aes(x = Station, fill = Usage)) +
                     geom_bar(position = 'stack') +
                     coord_flip() +
                     theme_bw() +
                     ylab('Trips') +
                     xlab('') +
                     theme(axis.text.x = element_text(angle = 45, hjust = 1))
                
ggplotly(station_gg)

```

Column {data-width=200}
-----------------------------------------------------------------------

### Median Trip Length

```{r}

median_min <- median(trips_df$duration_sec / 60) %>% round(digits = 1)

valueBox(median_min,
    caption = "Median Trip Duration (Minutes)",
    icon = "fa-clock-o",
    href = "#trip-duration")

```

### % Short Trips

```{r}

num_trips <- nrow(trips_df)
short_trips <- sum(trips_df$duration_sec < 600) # under 10 min
pct_short_trips <- round(100 * short_trips / num_trips, 0)

gauge(value = pct_short_trips,
      min = 0,
      max = 100,
      gaugeSectors(success = c(67,100), danger = c(0,32), warning = c(33,66))
     )

```

Column {data-width=300}
-----------------------------------------------------------------------

### Stations Map

```{r}
leaflet() %>%
  addTiles() %>%
  addMarkers(lat = stations_df$latitude, lng = stations_df$longitude)
```



Trip Duration
===================================== 

Column {data-width=600}
-----------------------------------------------------------------------

### Trip Durations

``` {r static_plot, fig.width = 10, fig.height=6}

duration_gg <- trips_df %>%
  mutate(`Trip Duration (min)` = duration_sec / 60) %>%
  filter(`Trip Duration (min)` <= 60) %>%
  ggplot(aes(x = `Trip Duration (min)`)) +
  theme_bw() +
  geom_histogram(binwidth = 1) +
  ylab('# Trips')


# Convert to interactive plot using plotly

ggplotly(duration_gg)

```

Column {data-width=400}
------------------------

```{r}



station_trips_df <- trips_df %>%
  select(start_station_name, end_station_name) %>%
  gather(key = Type, value = Station) %>%
  group_by(Station, Type) %>%
  summarize(n_trips = n()) %>% 
  mutate(Type = ifelse(Type == 'start_station_name', 'Trip Starts', 'Trip Ends')) %>%
  spread(key = Type, value = n_trips) %>%
  replace_na(list(`Trip Starts` = 0, `Trip Ends` = 0)) %>%
  mutate(Gap = `Trip Ends` - `Trip Starts`)
  
datatable(station_trips_df,
          rownames=FALSE,
          extensions = 'Buttons', 
          options = list(
                          dom = 'Bfrtip',
                          buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
                        )
          )

# kable(station_trips_df)

```

